name: Cypress Tests

on:
  push:
    branches: [ main ]

jobs:
  cypress-run:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        spec:
          # API
          - cypress/e2e/api/cadastro-api.cy.js
          - cypress/e2e/api/compra-api.cy.js
          - cypress/e2e/api/login-api.cy.js
          #autenticação
          - cypress/e2e/auth/login-api.cy.js
          - cypress/e2e/auth/login.cy.js
          - cypress/e2e/auth/signup-api.cy.js
          #e-commerce
          - cypress/e2e/ecommerce/compra-avancada.cy.js   
          - cypress/e2e/ecommerce/compra.cy.js
          - cypress/e2e/ecommerce/compra-avancada-com-mock.cy.js 
          #Fluxo completo
          - cypress/e2e/fluxo-completo.cy.js
    steps:
      - name: Checkout código
        uses: actions/checkout@v4

      - name: Cache node_modules
        uses: actions/cache@v4
        with:
          path: ~/.npm
          key: npm-${{ hashFiles('package-lock.json') }}

      - name: Rodar Cypress
        uses: cypress-io/github-action@v6
        with:
          spec: ${{ matrix.spec }}

      - name: Upload vídeos
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: videos
          path: cypress/videos

      - name: Upload reports
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: reports
          path: cypress/reports